create table if not exists public.sync_config(key text primary key,value text,updated_at timestamptz default now());
create table if not exists public.sync_runs(id bigint generated always as identity primary key,status text not null,started_at timestamptz default now(),finished_at timestamptz,cards_processed int default 0,cards_created int default 0,cards_updated int default 0,attachments_created int default 0,translations_created int default 0,error text);
create table if not exists public.list_map(source_list_id text primary key,destination_list_id text not null,source_name text,destination_name text,updated_at timestamptz default now());
create table if not exists public.card_map(source_card_id text primary key,destination_card_id text not null,source_list_id text,destination_list_id text,source_hash text,updated_at timestamptz default now());
create table if not exists public.label_map(source_label_id text primary key,destination_label_id text not null,source_name text,color text,updated_at timestamptz default now());
create table if not exists public.attachment_map(source_attachment_id text primary key,destination_attachment_id text,source_card_id text,destination_card_id text,name text,url text,updated_at timestamptz default now());
create table if not exists public.checklist_map(source_checklist_id text primary key,destination_checklist_id text not null,source_card_id text,destination_card_id text,updated_at timestamptz default now());
create table if not exists public.checkitem_map(source_checkitem_id text primary key,destination_checkitem_id text not null,source_checklist_id text,destination_checklist_id text,state text,updated_at timestamptz default now());
create table if not exists public.translation_cache(source_hash text primary key,source_text text not null,translated_text text not null,updated_at timestamptz default now());
alter table public.sync_config enable row level security;
alter table public.sync_runs enable row level security;
alter table public.list_map enable row level security;
alter table public.card_map enable row level security;
alter table public.label_map enable row level security;
alter table public.attachment_map enable row level security;
alter table public.checklist_map enable row level security;
alter table public.checkitem_map enable row level security;
alter table public.translation_cache enable row level security;
