create table if not exists sync_config (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists sync_runs (
  id bigint generated by default as identity primary key,
  status text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  cards_processed integer not null default 0,
  cards_created integer not null default 0,
  cards_updated integer not null default 0,
  attachments_created integer not null default 0,
  translations_created integer not null default 0,
  checklists integer not null default 0,
  error text
);

create table if not exists list_map (
  source_list_id text primary key,
  destination_list_id text not null,
  source_name text,
  destination_name text,
  updated_at timestamptz not null default now()
);

create table if not exists card_map (
  source_card_id text primary key,
  destination_card_id text not null,
  source_list_id text,
  destination_list_id text,
  source_hash text,
  updated_at timestamptz not null default now()
);

create table if not exists label_map (
  source_label_id text primary key,
  destination_label_id text not null,
  source_name text,
  color text,
  updated_at timestamptz not null default now()
);

create table if not exists attachment_map (
  source_attachment_id text primary key,
  destination_attachment_id text not null,
  source_card_id text,
  destination_card_id text,
  name text,
  url text,
  updated_at timestamptz not null default now()
);

create table if not exists checklist_map (
  source_checklist_id text primary key,
  destination_checklist_id text not null,
  source_card_id text,
  destination_card_id text,
  updated_at timestamptz not null default now()
);

create table if not exists checkitem_map (
  source_checkitem_id text primary key,
  destination_checkitem_id text not null,
  source_checklist_id text,
  destination_checklist_id text,
  state text,
  updated_at timestamptz not null default now()
);

create table if not exists translation_cache (
  source_hash text primary key,
  source_text text not null,
  translated_text text not null,
  updated_at timestamptz not null default now()
);

create table if not exists sync_state (
  id bigint primary key default 1,
  cursor_list_index integer not null default 0,
  cursor_card_index integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into sync_state (id, cursor_list_index, cursor_card_index)
values (1, 0, 0)
on conflict (id) do nothing;

create index if not exists sync_runs_started_idx on sync_runs (started_at desc);
create index if not exists card_map_destination_idx on card_map (destination_card_id);
create index if not exists attachment_map_card_idx on attachment_map (source_card_id);
